### ISSUE TITLE
Chore: 로컬 개발 환경 구축

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#1]
## IssueName
로컬 개발 환경 구축

## Description
Springboot + Docker 로컬 개발 환경 구축

## Todo
 - [x] Spring 프로젝트 생성
 - [x] Docker-MySQL 연결
 - [x] Docker-Redis 연결
 - [x] Swagger UI 설정
