### ISSUE TITLE
Refactor: Lecture 구조 변경 및 API 업데이트

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#109]
## IssueName
Lecture 구조 변경 및 API 업데이트

## Description
Lecture Entity에 학년/과목과 관련된 정보 추가 필요
이에 따른 관련 API 모두 수정

## Todo
 - [x] Lecture Table Column 추가
 - [x] Lecture Entity 수정
 - [x] Lecture 관련 DTO 수정
 - [x] Lecture 관련 API 수정
 - [x] 메인 페이지에서 Lecture 메타 정보 반환 시, 내보낸 학생은 반환되지 않도록 수정
