### ISSUE TITLE
Refactor: Lesson 구조 변경 및 API 업데이트

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#110]
## IssueName
Lesson 구조 변경 및 API 업데이트

## Description
Lesson Table에서 json type인 Schedule 칼럼이 정렬이 불가능해지므로, 쪼개서 세분화 필요
이에 따른 관련 API 모두 수정

## Todo
 - [x] Lesson Table에 weekday, startTime, endTime 칼럼 추가
 - [x] Lesson Entity 수정
 - [x] Lesson 관련 DTO 수정
 - [x] Lesson 관련 API 수정
