### ISSUE TITLE
Chore: Dev Infra 구축 및 연동 확인

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#13]
## IssueName
Dev Infra 구축 및 연동 확인

## Description
Dev 환경에 대한 AWS Infra 구축 및 테스트 진행

## Todo
- [x] CI 스크립트 제작 및 테스트
- [x] AWS RDS 연동
- [x] AWS ElasticBeanstalk와 Repository 연동
- [x] CD 스크립트 제작 및 테스트
- [x] 클라이언트단에서 접속 및 Swagger 테스트 가능 여부 확인
