### ISSUE TITLE
Feat: 문제집 API 개발

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#138]
## IssueName
문제집 API 개발

## Description
콘텐츠 플랫폼 앱 내 도입하므로, 관련 엔티티 생성 및 API 개발 필요
초기에는 뷰어 형식으로 제공할 예정이므로, 풀이 / 통계와 관련된 파트는 개발하지 않음
꿀팁/영상 부분은 노션 링크로 대체할 예정
초기에는 직접 문제 삽입이 아닌, 문제집 단위의 파일을 업로드할 예정이므로, 문제집 파트만 개발
추후, 문제 파트 개발 예정

## Todo
 - [x] 문제집 ERD 설계
 - [x] 문제집 Entity 생성
 - [x] 문제집 API 개발
