### ISSUE TITLE
Feat: Member, Lecture 간 참조 테이블 연동

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#14]
## IssueName
Member, Lecture 간 참조 테이블 연동

## Description
Member, Lecture 간 N:M 관계이므로 참조 테이블 구성 및 연동

## Todo
 - [x] Class Entity 이름 변경 (Java의 class와 이름 충돌 발생) -> Lecture로 변경
 - [x] MemberAndClass 참조 Entity 생성
 - [x] Class Entity 생성 (Json 타입 처리 방안 확인 필요)
 - [x] Member와 MemberAndClass 1:N 연결
 - [x] Class와 MemberAndClass 1:N 연결
 - [x] Class 생성 API
 - [x] Class 수정 API
 - [x] Class 삭제 API
 - [x] Class 반환 API
