### ISSUE TITLE
Fix: 학생 초대 로직 수정

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#153]
## IssueName
학생 초대 로직 수정

## Description
여러 클래스에서 중복 초대 시, 한 계정이 아닌 여러 계정으로 생성되는 오류 수정
학생을 초대했다 취소하는 경우, 해당 초대상태의 계정 논리적 삭제가 되도록 수정
탈퇴한 학생은 학생관리에서 조회되지 않도록 수정

## Todo
 - [x] 이미 초대된 계정 존재 시, 해당 계정으로 다시 초대되도록 연결
 - [ ] 학생을 초대했다 취소하는 경우, 초대 상태 계정 논리적 삭제 되도록 수정
 - [x] 탈퇴 학생은 학생관리에서 조회되지 않도록 쿼리 수정
