### ISSUE TITLE
Chore: Response 관련 응답 메세지 변경

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#17]
## IssueName. 
Chore: Application, Valid 관련 에러 응답 메세지 변경

## Description
Application단에서의 오류와 사용자 전송 객체의 유효성 오류 발생 시, 이에 대한 에러 메세지를 사용자화

## Todo
 - [x] ApplicationException 설정
 - [x] 기존 RuntimeException으로 선언된 오류 메세지 수정
 - [x] Valid 관련 Exception 수정
 - [x] 기존 Valid 검증 필요 전송 객체 수정
 - [x] 응답 객체에서의 Long 자료형에 해당하는 값들 String 자료형으로 변경
