### ISSUE TITLE
Fix: QA 진행 결과에 따른 오류 업데이트

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#173]
## IssueName
QA 진행 결과에 따른 오류 업데이트

## Description
QA  0.2.1 버전 진행 결과에 메이저 버그 (초대 학생 내보내기 쿼리 오류, 기존 초대 완료 학생 중복 초대 가능), 기타 업데이트 사항(오탈자, 수업 리포트 수정 API 조건 추가) 수정 진행

## Todo
 - [x] 수업 리포트 수정 API 변경
 - [x] 기존 초대 완료된 학생 중복 초대 불가능하도록 막기
 - [x] 초대된 학생 내보내기 잘못된 쿼리 수정
 - [x] 서버 전송 문자 오탈자 수정
