### ISSUE TITLE
Fix: Workbook API 오류 수정

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#197]
## IssueName
Workbook API 오류 수정

## Description
Workbook API 중 페이지네이션 오류, 업로드 관련 일부 오류 확인 및 수정

## Todo
 - [x] switch문 case별 break 추가
 - [x] MySQL 예약어랑 겹쳐서 제대로 동작하지 않는 오류 수정
 - [x] 페이지네이션 API 오류 수정
