### ISSUE TITLE
Feat: WorkbookRes 반환 데이터 추가 & 조회수 로직 적용

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#202]
## IssueName
WorkbookRes 반환 데이터 추가  & 조회수 로직 적용

## Description
WorkbookRes에 마지막 업데이트용 데이터가 필요함에 따라 반환 정보 추가
Get API 요청 시, 조회수 증가하도록 추가

## Todo
 - [x] WorkbookRes Dto 변경
 - [x] 관련 쿼리 변경
 - [x] 조회수 증가 로직 적용
