### ISSUE TITLE
Fix: 썸네일 이미지, 카드 이미지 분리

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#209]
## IssueName
썸네일 이미지, 카드 이미지 분리

## Description
WorkbookRes의 썸네일 이미지는 원본파일이지만, WorkbookCardRes의 썸네일 이미지는 3배 축소된 비율을 활용해야 페이제닝션 과정에서 이미지 로딩으로 인한 버벅임이 사라짐.
이에 따라, 원본 파일을 전달받았을 때, 3배 축소 리사이징하는 이미지를 별도로 생성하여 처리하는 로직 구현 및 관련 API에 적용

## Todo
 - [ ] 이미지 리사이징 메소드 개발
 - [ ] WorkbookEntity에 칼럼 추가
 - [ ] WorkbookCardRes를 반환하는 API 쿼리에 추가된 칼럼으로 반환하도록 적용
