### ISSUE TITLE
Fix: FCM 비공개 키 Json 파일 Exception

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#276]
## IssueName
FCM 비공개 키 Json 파일 Exception

## Description
1. Firebase 비공개 키를 Github Actions Secrets에 저장
2. CD 스크립트 수행 시, 주입받아서 resources/firebase 위치에 저장
3. FCMConfig시 InputStream으로 변환
4. MalformedJsonException 발생
위와 같은 상황이나, serialize하여 yml에 암호화 후 적용 시, 정상 적용됨.

## Todo
 - [ ] 로컬과 EC2간, 인코딩의 차이 확인하기 (EB 이슈일 수 있음.)
 - [x] syntaxerror 원인 분석해보기
 - [ ] 기존 방식 재시도

----
해결: Service key의 줄바꿈을 Github Actions의 Secrets에서는 인식할 수 없기에 발생하는 문제로 보임. Base64 인코딩 후 적용하여 해결
