### ISSUE TITLE
Fix: Task, Lecture 비즈니스 로직 수정

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#29]
## IssueName
Task, Lecture 비즈니스 로직 수정

## Description
비즈니스 로직 변경에 따른 Banner, Task 주요 업데이트 로직 수정

## Todo
 - [x] 수업 일정 미등록 시, 등록 가능하도록 유효성 검증 로직 삭제
 - [x] BannerRes String -> Long 변경
 - [x] TaskRes String -> Long 변경
 - [x] TaskRes에 color 데이터 추가
 - [x] Lecture 삭제 시, 관련된 Task, Homework, Lesson 삭제되도록 로직 수정
