### ISSUE TITLE
Feat: Log 연동

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#31]
## IssueName
API Path별 로그 연동

## Description
주 사용 기능들을 확인하기 위한 API별 로그 연동

## Todo
 - [x] Log Table 설계
 - [x] Log Entity
 - [x] Log 생성 로직
 - [ ] 각 API별 Log 추가 로직 붙이기
