### ISSUE TITLE
Chore: Sonarqube + Jacoco 적용

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#316]
## IssueName
Sonarqube + Jacoco 적용

## Description
정적 코드 분석을 위한 소나큐브 도입

## Todo
 - [ ] Local에서 도커로 Sonarqube 연동
 - [ ] Jacoco 설정 진행
 - [ ] Sonarqube 관련 설정 진행
 - [ ] 테스트 코드 작성
 - [ ] 코드 분석 진행
