### ISSUE TITLE
Fix: Lesson & Lecture 관련 API 수정

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#34]
## IssueName
Lesson & Lecture 관련 API 수정

## Description
디자인 상 추가 구현 및 수정이 필요한 부분 확인되어 해당 부분 수정 진행

## Todo
 - [x] 기존 구현된 Lesson API 수정
 - [x] Lesson 등록 API에 숙제 데이터 포함
 - [x] Lesson 수정 API에 숙제 데이터 포함
 - [x] Lesson 특정 하나의 전체 데이터 반환 API
 - [x] Lesson 모두 등록, 모두 수정 API
 - [x] 월별 수업 정보 반환 API
 - [x] 진도 관련 데이터 반환 분리 
 - [x] Lecture Entity 변경
 - [x] Lecture CRUD API 변경
 - [ ] 할 일, 수업 리포트, 진도 페이지네이션 구현 (미확정)
