### ISSUE TITLE
Fix: 게시글 오류 수정

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#377]
## IssueName
게시글 오류 수정

## Description
클라이언트 테스트 과정에서 아래 오류 발생에 따른 오류 수정
1. 게시글수정api 결과 반환값에 새로 첨부한 파일 말고 기존게시글에 있던 파일은 포함 안 돼있음
2. 파일 여러개 첨부하여 댓글 작성 -> 댓글이 여러개 작성된걸로 보임(각 댓글마다 첨부파일이 하나씩)
3. 게시글이 작성자한테밖에 안보임

## Todo
 - [x] 게시글 수정 API의 반환값 오류 수정
 - [x] 댓글 조회 쿼리 수정
 - [x] 게시글 권한 확인
