### ISSUE TITLE
Feat: 가계정 생성 및 회원가입 로직 변경 (9월 예정)

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#39]
## IssueName
가계정 생성 및 회원가입 로직 개발

## Description
학생 초대하기, 임시 학생 계정 생성 관련 비즈니스 로직 개발

## Todo
 - [x] 가계정 관련 Member Column 추가
 - [x] 가계정 생성 API
 - [x] 학생 내보내기 API
 - [x] 회원가입 시, 가계정 존재 여부 확인 비즈니스 로직 추가
 - [x] 회원탈퇴 후, 재가입 허용하도록 로직 추가
 - [x] 학생 초대 API
 - [x] 학생 관리 페이지 정보 반환 API
