### ISSUE TITLE
Chore: GCP -> AWS 전환

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#421]
## IssueName
과릿 README.md 작성

## Description
과릿 개발 관련 문서 정리를 위해 README.md 작성

## Todo
 - [x] ECR 생성
 - [x] 자동화 배포 파이프라인 구축
 - [x] 자동화 배포 파이프라인 테스트
 - [x] DB, Redis 파일 동기화
