### ISSUE TITLE
Refactor: Redis 과의존 개선

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#445]
## IssueName
Redis 과의존 개선

## Description
Redis에 온전히 일임했던, 인증번호 저장 등의 로직이 Redis 장애 시의 대응방법이 없으므로 이를 해결하고자 진행

## Todo
 - [x] Redis 사용하는 데이터들에 대한 테이블 생성
 - [x] MySQL 저장하는 로직 개발
 - [x] Redis 헬스체크 도입하여, 장애 대응 가능하도록 리팩토링
