### ISSUE TITLE
Refactor: 프로젝트 구조 개선

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#449]
## IssueName
프로젝트 구조 개선

## Description
기존 계층형 아키텍처에서, 멀티 모듈로 개선
- Common 모듈
- Repoistory + DB 모듈
- External 모듈 (SMS, FCM)
- Batch 모듈
- API 모듈 (최상단)

> 개선 이유: 알림/배치 등 관리의 포인트가 많은 로직 다수이나, 계층형 안에 마구잡이로 들어 있어, 파악하기 어려움

## Todo
 - [x] 멀티 모듈 생성
 - [x] 모듈별 파일 분리
 - [x] QA 처음부터 재진행 
 - [x] 일부 코드 리팩토링
