### ISSUE TITLE
Hotfix: EBS 볼륨 확장 및 FCM 오류 수정

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#462]
## IssueName
EBS 볼륨 확장 및 FCM 오류 수정

## Description
기존의 8GB EBS로 유지하는 상황에서, `/dev/root` 경로인 루트 경로에 많은 데이터가 쌓여서 더 이상 견딜 수 없는 상황이 되었음을 확인하여, EBS 볼륨을 30GB로 확장하며 이를 적용

## Todo
 - [x] EBS 볼륨 30GB 확장
 - [x] EC2 내 볼륨 확장 연동
 - [x] FCM 경로 오류 수정

**레퍼런스**
- [EBS 볼륨 업데이트 기술 블로그](https://velog.io/@holawan/EC2-%ED%94%84%EB%A6%AC%ED%8B%B0%EC%96%B4%EB%A1%9C-%EB%B0%9B%EC%9D%80-Ubuntu-%EC%9A%A9%EB%9F%89-%ED%99%95%EC%9E%A5)
