### ISSUE TITLE
Fix: 유효성 검증 & 쿼리 수정

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#48]
## IssueName
유효성 검증 & 조회 쿼리 수정

## Description
- Task 등록 시 Long type 변수에 String으로 요청해도 바인딩 되는 것에 대한 유효성 검증
- Class Main Page용 조회 쿼리 수정
- Homework Post시 null값 비허용
- 진도리스트 반환 시, 추가 정보 포함

## Todo
 - [ ] 유효성 검증 로직 확인
 - [x] Task 조회 쿼리 수정
 - [x] Schedule의 weekday를 ENUM으로 관리
 - [x] HomeworkReq NotNull 어노테이션 적용
 - [x] 진도리스트 반환 시, Time 데이터 포함 반환
