### ISSUE TITLE
Feat: Auth API 개발

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#5]
## IssueName
Auth API

## Description
인증 관련 로직에 대한 설정 및 API 개발

## Todo
 - [x] BaseEntity 설정
 - [x] SHA 256 설정
 - [x] Member Entity
 - [x] 일반 회원가입 API
 - [x] JWT Configuration
 - [x] 일반 로그인 API
 - [x] 로그아웃 API
 - [x] 토큰 재발급 API
