### ISSUE TITLE
Fix: Lesson 생성 로직 & 조회 로직 수정 (중간 점검 이후 진행)

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#50]
## IssueName
Lesson 생성 로직 & 조회 로직 수정

## Description
Lesson 생성 및 조회 로직 정립 및 수정

## Todo
 - [x] Lesson 생성 로직 재정립
 - [x] Lesson 생성 로직 수정
 - [x] Lecture 페이지용 Lesson 메타 정보 조회 시 쿼리 수정 및 정렬 로직 정립
