### ISSUE TITLE
Feat: 공지사항, 문의하기 연결 API

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#52]
## IssueName
공지사항, 문의하기 연결 API

## Description
공지사항, 문의하기 연결 API

## Todo
 - [x] 설정용 Entity 생성
 - [x] 설정 Table 생성
 - [x] 설정 정보 등록 API
 - [x] 설정 정보 수정 API
 - [x] 설정 정보 삭제 API
 - [x] 설정 정보 반환 API
