### ISSUE TITLE
Chore: Sentry 연동 & 인증 로직 수정

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#71]
## IssueName
Chore: Sentry 연동 & 인증 로직 수정

## Description
Chore: Sentry 연동 & 인증 로직 수정

## Todo
 - [x] 로그아웃 후, 동일 액세스 토큰으로 재로그인 불가하도록 수정
 - [x] Sentry + Springboot 연동
 - [x] Sentry Slack 연동
