### ISSUE TITLE
Chore: 운영 서버 환경 설정

### ISSUE THREAD

**Issue by dl-00-e8** [self-runner/gwalit-server#95]
## IssueName
운영 서버 환경 설정

## Description
운영 서버 환경 구축 및 설정 진행

## Todo
 - [x] 운영 서버용 yml 암호화
 - [x] release branch용 github actions scripts 작성
 - [x] 운영 서버 작동 테스트
